import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Search, ArrowUpRight } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50 w-full max-w-[980px] px-4">
          {/* Outer gradient border container */}
          <div
            className="relative rounded-[40px] p-px"
            style={{
              background:
                "linear-gradient(180deg, rgb(33, 33, 33) 0%, rgba(33, 33, 33, 0.4) 100%)",
            }}
          >
            {/* Inner content container */}
            <nav className="bg-[rgb(5,5,5)] rounded-[40px] px-6 py-4">
              <div className="flex items-center justify-between">
                {/* Logo */}
                <a href="./" className="flex-shrink-0">
                  <img
                    src="https://framerusercontent.com/images/BaSvDfQZfE4UubCPmSB77sRFkY.png?width=2663&height=601"
                    alt="Canadian Game Changers"
                    className="h-[26px] w-auto object-contain"
                  />
                </a>

                {/* Navigation Links */}
                <div className="hidden lg:flex items-center gap-8 mx-8">
                  <a
                    href="./"
                    className="text-white hover:text-white text-[15px] font-medium transition-colors duration-200"
                    style={{ fontFamily: "Manrope, sans-serif" }}
                  >
                    Home
                  </a>
                  <a
                    href="./ehgameexpo"
                    className="text-white hover:text-white text-[15px] font-medium transition-colors duration-200"
                    style={{ fontFamily: "Manrope, sans-serif" }}
                  >
                    Eh! Game
                  </a>
                  <a
                    href="./categories"
                    className="text-white hover:text-white text-[15px] font-medium transition-colors duration-200"
                    style={{ fontFamily: "Manrope, sans-serif" }}
                  >
                    Nominees
                  </a>
                  <a
                    href="./partners"
                    className="text-white hover:text-white text-[15px]  transition-colors duration-200 font-medium"
                    style={{ fontFamily: "Manrope, sans-serif" }}
                  >
                    Partners
                  </a>
                  <button
                    className="text-white text-[15px] font-medium"
                    style={{ fontFamily: "Manrope, sans-serif" }}
                  >
                    More
                  </button>
                </div>

                {/* Right Actions */}
                <div className="flex items-center gap-3">
                  {/* Search Button */}
                  <button
                    className="w-10 h-10 flex items-center justify-center rounded-[10px] hover:bg-white/5 transition-colors duration-200"
                    aria-label="Search"
                  >
                    <Search
                      className="w-6 h-6 text-[rgb(69,22,130)]"
                      strokeWidth={2}
                    />
                  </button>

                  {/* Sign Up Button with Glow Effect */}
                  <a
                    href="https://cgameawards.com/#:~:text=Be,Tickets"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="relative group"
                  >
                    {/* Button Container */}
                    <div className="relative bg-[rgb(32,32,32)] rounded-[7px] px-5 py-2.5 overflow-hidden">
                      {/* Animated Stroke */}
                      <div
                        className="absolute inset-0 rounded-[7px] opacity-100 transition-transform duration-300 group-hover:scale-105"
                        style={{
                          background:
                            "radial-gradient(18.117% 45.653% at 0% 63%, rgb(77, 183, 185) 0%, rgba(255, 255, 255, 0) 100%)",
                          transform:
                            "translate3d(-6.3px, 0px, 0px) scale(0.928, 1)",
                        }}
                      />

                      {/* Glow Effect */}
                      <div
                        className="absolute inset-0 rounded-[7px] blur-[15px] opacity-60 transition-transform duration-300 group-hover:scale-110"
                        style={{
                          background:
                            "radial-gradient(25% 40.172% at 0% 63%, rgb(77, 183, 185) 0%, rgba(255, 255, 255, 0) 100%)",
                          transform:
                            "translate3d(-8.82px, 0px, 0px) scale(0.8992, 1)",
                        }}
                      />

                      {/* Dark Fill */}
                      <div className="absolute inset-0 bg-[rgb(13,13,13)] rounded-[7px]" />

                      {/* Content */}
                      <div className="relative flex items-center gap-2">
                        <span
                          className="text-[rgb(222,222,222)] text-[15px] font-normal whitespace-nowrap"
                          style={{ fontFamily: "Manrope, sans-serif" }}
                        >
                          Sign up for tickets
                        </span>
                        <ArrowUpRight
                          className="w-5 h-5 text-[rgb(222,222,222)] transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5"
                          strokeWidth={2}
                        />
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            </nav>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
