import CategoriesGrid from '@/components/CategoriesGrid';
import CategoriesHero from '@/components/CategoriesHero';
import NomineeSection from '@/components/NomineeSection';

const allCategories = [
  {
    id: 'bestartdirection',
    title: 'Best Art Direction',
    description:
      'The Canadian Game Award for Best Art Direction recognizes the achievement for an art direction in games. Judges will be looking at the quality of the visual and its consistency across all aspects of game production. They will look at the visual signature, its uniqueness, the animation, rendering and impact on storytelling, as well as its high level of immersion in the game environment or story.',
    nominees: [
      {
        id: '1',
        title: 'South of Midnight',
        studio: '33 Immortals',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Lost Records: Bloom & Rage',
        studio: 'Eternal Strands',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: 'Marvel Cosmic Invasion',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Marvel Cosmic Invasion',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
      {
        id: '5',
        title: "Assassin's Creed Shadows",
        studio: '',
        imageUrl: '/images/nominees/7pdJpCtGMn2TFeYMS5iUM6LfeNg.avif',
        link: 'https://store.steampowered.com/app/2153750/Venture_to_the_Vile/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestgamedesign',
    title: 'Best Game Design',
    description:
      'The Canadian Game Award for Best Game Design recognizes the achievement for game design in a video game. It looks at its innovative side, its features depending on the platform, the experience it offers as well as its level of engagement in a genre, or if it defines a new genre/new standards.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Hell is Us',
        imageUrl: '/images/nominees/qBq5kM8Jw2SNLnqhhX5BPPkmS30.avif',
        link: 'https://store.steampowered.com/app/2379780/Balatro/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'Eternal Strands',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: 'South of Midnight',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'South of Midnight',
        studio: 'Battlefield 6',
        imageUrl: '/images/nominees/srdhmkMJaMJZewKTEbDfYzW9ho.avif',
        link: 'https://store.steampowered.com/app/1864950/Beastieball/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: '',
        imageUrl: '/images/nominees/qUC7vhHQtMPH10s2Gd43Fpjfc.avif',
        link: 'https://store.steampowered.com/app/1304930/The_Outlast_Trials/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestscore',
    title: 'Best Score/Soundtrack',
    description:
      'The Canadian Game Award for Best Score/Soundtrack recognizes the achievement for a game soundtrack. It has to present a high quality of integration within the game as well as its impact on the game experience.',
    nominees: [
      {
        id: '1',
        title: 'South of Midnight',
        studio: 'Lost Records: Bloom & Rage',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Lost Records: Bloom & Rage',
        studio: 'Eternal Strands',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: "Assassin's Creed Shadows",
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '4',
        title: "Assassin's Creed Shadows",
        studio: 'Marvel Cosmic Invasion',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Marvel Cosmic Invasion',
        studio: '',
        imageUrl: '/images/nominees/5ujWG1mHqDpjhlBtf2rGwJ7Y.avif',
        link: 'https://store.steampowered.com/app/2113850/Spirit_City_Lofi_Sessions/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestperformance',
    title: 'Best Performance',
    description:
      'The Canadian Game Award for Best Performance recognizes the achievement for character performance in a game. It has to demonstrate an original, creative and engaging performance that creates an indelible impression and contributes to a compelling experience. The judges will also consider the quality of voice artistry and motion capture (if applicable).',
    nominees: [
      {
        id: '1',
        title: 'Elias Toufexis (Hell is Us)',
        studio: "Peter Shinkoda (Assassin's Creed Shadows)",
        imageUrl: '/images/nominees/JzVYu1RKeJoWstyzCopS1B7KE.avif',
        link: 'https://www.imdb.com/name/nm8744341/',
        isWinner: false,
      },
      {
        id: '2',
        title: "Peter Shinkoda (Assassin's Creed Shadows)",
        studio: 'Olivia Lepore (Bloom & Rage)',
        imageUrl: '/images/nominees/rgqnSnqhtaNqN9M8pLBRGICOA.avif',
        link: 'https://www.imdb.com/name/nm2785427/?ref_=fn_all_nme_1',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Olivia Lepore (Bloom & Rage)',
        studio: 'Erica Luttrell (Battlefield 6)',
        imageUrl: '/images/nominees/6vnZRxObnGkdwEIkAyJAwW3qq44.avif',
        link: 'https://music.apple.com/us/song/moving-houses-credits/1766965099',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Erica Luttrell (Battlefield 6)',
        studio: "Momona Tamada (Assassin's Creed Shadows)",
        imageUrl: '/images/nominees/dx5BpL3KqGPgYSgTCrUGtNvWb7s.avif',
        link: 'https://www.imdb.com/name/nm2233310/?ref_=fn_all_nme_1',
        isWinner: false,
      },
      {
        id: '5',
        title: "Momona Tamada (Assassin's Creed Shadows)",
        studio: '',
        imageUrl: '/images/nominees/JzVYu1RKeJoWstyzCopS1B7KE.avif',
        link: 'https://www.imdb.com/name/nm8744341/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestnarrative',
    title: 'Best Narrative',
    description:
      'The Canadian Game Award for Best Narrative recognizes the achievement for a game narrative. It will be awarded based on the story and vision, as well as the dialogues (if applicable) and the emotional impact of the story on the player.',
    nominees: [
      {
        id: '1',
        title: 'Lost Records: Bloom & Rage',
        studio: 'Hell is Us',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'South of Midnight',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: "Assassin's Creed Shadows",
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '4',
        title: "Assassin's Creed Shadows",
        studio: 'Wanderstop',
        imageUrl: '/images/nominees/srdhmkMJaMJZewKTEbDfYzW9ho.avif',
        link: 'https://store.steampowered.com/app/1864950/Beastieball/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Wanderstop',
        studio: '',
        imageUrl: '/images/nominees/qUC7vhHQtMPH10s2Gd43Fpjfc.avif',
        link: 'https://store.steampowered.com/app/1304930/The_Outlast_Trials/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestaudiodesign',
    title: 'Best Audio Design',
    description:
      'The Canadian Game Award for Best Audio Design recognizes the achievement for audio design in a game. Judges will be looking at its coherence with the title/brand, its immersiveness, quality of integration and of composition.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Hell is Us',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'South of Midnight',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: 'Eternal Strands',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Eternal Strands',
        studio: 'Battlefield 6',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: '',
        imageUrl: '/images/nominees/5ujWG1mHqDpjhlBtf2rGwJ7Y.avif',
        link: 'https://store.steampowered.com/app/2113850/Spirit_City_Lofi_Sessions/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsplayer',
    title: 'Best Esports Player',
    description:
      'The Canadian Game Award for Esports Player recognizes the impact of an esport player within their community, and their overall performance in the game they play.',
    nominees: [
      {
        id: '1',
        title: 'Dashy',
        studio: 'Russel "Twistzz" Van Dulken',
        imageUrl: '/images/nominees/cCZEzgrFYaLjyQBoAdgJlRZsiyw.avif',
        link: 'https://x.com/sarah_frags?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Russel "Twistzz" Van Dulken',
        studio: 'Canadian – Troy',
        imageUrl: '/images/nominees/oYeEPBOsicqkqtnvmjEtgfNpny4.avif',
        link: 'https://x.com/Twistzz',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Canadian – Troy',
        studio: 'Mada (Adam)',
        imageUrl: '/images/nominees/eN8KprL1c8aTrZ1iiWKkj0VnQ.avif',
        link: 'https://x.com/onfirescarlett?lang=en',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Mada (Adam)',
        studio: 'Sarah Simpson (Shopify Rebellion Gold)',
        imageUrl: '/images/nominees/ZDUR4ZDcFeWTbudNeGrWCuyk.avif',
        link: 'https://x.com/TenZOfficial',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Sarah Simpson (Shopify Rebellion Gold)',
        studio: '',
        imageUrl: '/images/nominees/p9COOGjEuOR4JTXmShhNKCcuG20.avif',
        link: 'https://x.com/Arteezy',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsevent',
    title: 'Best Esports Event',
    description:
      'The Canadian Game Award for Esports Event recognizes the tournament organizers that had a big impact on the Canadian community, and offered an outstanding production quality with high entertainment value.',
    nominees: [
      {
        id: '1',
        title: 'Valorant Masters Toronto 2025',
        studio: 'Electric Clash 2025',
        imageUrl: '/images/nominees/BO90OOsTVVVKEwQym2dqH4I1lM.avif',
        link: 'https://x.com/Incendium_GG',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Electric Clash 2025',
        studio: 'Battle of BC 7',
        imageUrl: '/images/nominees/jji9avxtnq1U56Y4RDxvOUyxuw.avif',
        link: 'https://callofdutyleague.com/en-us/events/ultra-major',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Battle of BC 7',
        studio: 'Raptors GC Tournament',
        imageUrl: '/images/nominees/FL2gDHAdPKJYSl0fmk4yUaduxU.avif',
        link: 'https://bellesportschallenge.ca/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Raptors GC Tournament',
        studio: 'Call of Duty Champs',
        imageUrl: '/images/nominees/Bk5o7NAvPfShDualM81BAbbomAs.avif',
        link: 'https://x.com/battleofbc?lang=en',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Call of Duty Champs',
        studio: '',
        imageUrl: '/images/nominees/NU4cvhcp1T9nmXPNuxxzlhDEees.avif',
        link: 'https://www.ubisoft.com/fr-ca/esports/rainbow-six/siege/news-updates/3B2zPQqqn23gVCY38zHrzK/welcome-the-blast-r6-montreal-major',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportscoach',
    title: 'Best Esports Coach',
    description:
      'The Canadian Game Award for Esports Coach recognizes excellence in coaching and team development within the esports community.',
    nominees: [
      {
        id: '1',
        title: 'Loic "Effys" Sauvageau',
        studio: 'Antonin Tran (AEC)',
        imageUrl: '/images/nominees/0hfu5ou1r0O3kYDsMNmYkTUj4.avif',
        link: 'https://x.com/cecefps?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Antonin Tran (AEC)',
        studio: 'Mervin-Angelo "Dayos" Lachica',
        imageUrl: '/images/nominees/TmHpFPmatSIX3DJ5vRErXw7yvI.avif',
        link: 'https://x.com/NickEh30',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Mervin-Angelo "Dayos" Lachica',
        studio: 'Shaun Byrne (St. Clair College)',
        imageUrl: '/images/nominees/EZzcvAWXr8m8K1IW52GaEKvMnAM.avif',
        link: 'https://x.com/Aiekillu',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Shaun Byrne (St. Clair College)',
        studio: 'Aui_2000',
        imageUrl: '/images/nominees/2kGrWreM0iLbyWTtTLzNr5Oqu4.avif',
        link: 'https://x.com/AshleyRoboto',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Aui_2000',
        studio: '',
        imageUrl: '/images/nominees/5PZJDm6fjCbTcXoszamLJEzgs.avif',
        link: 'https://x.com/pokimanelol',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsorg',
    title: 'Best Esports and Gaming Organization',
    description:
      'The Canadian Game Award for Esports Org recognizes the engagement and positive impact in their community, as well as their overall player performances across games.',
    nominees: [
      {
        id: '1',
        title: 'Shopify Rebellion',
        studio: 'Toronto Ultra / KOI / OverActive Media',
        imageUrl: '/images/nominees/lxCjygj0yiSSL79Z1meNl2V7vw.avif',
        link: 'https://www.instagram.com/cocottee._',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Toronto Ultra / KOI / OverActive Media',
        studio: 'Vancouver Surge',
        imageUrl: '/images/nominees/IIcKYBLemTH97e6821rbfFTB0jA.avif',
        link: 'https://www.instagram.com/lewislefou/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Vancouver Surge',
        studio: 'Raptors GC',
        imageUrl: '/images/nominees/Kdxi1PhGMEdEDQGhFFH27ePOo.avif',
        link: 'https://www.instagram.com/achillefps/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Raptors GC',
        studio: '',
        imageUrl: '/images/nominees/eRVEKR8ojKxbDygtmSAZMO8Jg.avif',
        link: 'https://www.instagram.com/madamezoum/',
        isWinner: false,
      },
      {
        id: '5',
        title: '',
        studio: '',
        imageUrl: '/images/nominees/UHbE05jVw7MaYV4OLIyLrGoE2U.avif',
        link: 'https://www.instagram.com/mathieupellerin._/?hl=en',
        isWinner: false,
      },
    ],
  },
  {
    id: 'contentcreator',
    title: 'Best Content Creator/Show',
    description:
      'The Canadian Game Award for Content Creator/Show recognizes a TV Show, Web Show, or Web Clips that have a big impact on the gaming industry or community, and have an outstanding entertainment value.',
    nominees: [
      {
        id: '1',
        title: 'Victor Lucas / Electric Playground',
        studio: 'NickEh30 (Nicholas Amyoony)',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'NickEh30 (Nicholas Amyoony)',
        studio: 'Shroud (Michael Grzesiek)',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Shroud (Michael Grzesiek)',
        studio: 'Stef Sanjati',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Stef Sanjati',
        studio: 'Typical Gamer (Andre Rebelo)',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Typical Gamer (Andre Rebelo)',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'beststreamer',
    title: 'Best Streamer',
    description:
      'The Canadian Game Award for Best Streamer recognizes excellence in live streaming and content creation within the gaming community.',
    nominees: [
      {
        id: '1',
        title: 'Shroud (Michael Grzesiek)',
        studio: 'xQc (Felix Lengyel)',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'xQc (Felix Lengyel)',
        studio: 'NickEh30 (Nicholas Amyoony)',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'NickEh30 (Nicholas Amyoony)',
        studio: 'Typical Gamer (Andre Rebelo)',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Typical Gamer (Andre Rebelo)',
        studio: 'Ashley Roboto',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Ashley Roboto',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestpersonality',
    title: 'Best Personality',
    description:
      'The Canadian Game Award for Best Personality recognizes individuals who have made significant contributions to the gaming community through their engaging personalities and content.',
    nominees: [
      {
        id: '1',
        title: 'Jennifer Pitchette (LemonKiwi)',
        studio: 'Victor Lucas',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Victor Lucas',
        studio: 'Stef Sanjati',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Stef Sanjati',
        studio: 'Vansilli / Alex "Vansilli" Nguyen',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Vansilli / Alex "Vansilli" Nguyen',
        studio: 'Shroud (Michael Grzesiek)',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Shroud (Michael Grzesiek)',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestpcgame',
    title: 'Best PC Game',
    description:
      'The Canadian Game Award for Best PC Game recognizes excellence in PC gaming, considering factors like gameplay, graphics, innovation, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: 'Aloft',
        studio: 'Foundation',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Foundation',
        studio: 'Ambrosia Sky: Act One',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Ambrosia Sky: Act One',
        studio: 'Eternal Strands',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Eternal Strands',
        studio: 'Battlefield 6',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestconsolegame',
    title: 'Best Console Game',
    description:
      'The Canadian Game Award for Best Console Game recognizes excellence in console gaming, considering factors like gameplay, graphics, innovation, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'South of Midnight',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'South of Midnight',
        studio: 'Battlefield 6',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Battlefield 6',
        studio: 'Marvel Cosmic Invasion',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Marvel Cosmic Invasion',
        studio: 'Hell is Us',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Hell is Us',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestmobilegame',
    title: 'Best Mobile Game',
    description:
      'The Canadian Game Award for Best Mobile Game recognizes excellence in mobile gaming, considering factors like gameplay, graphics, innovation, and overall player experience on mobile platforms.',
    nominees: [
      {
        id: '1',
        title: 'Elsewhere Electric',
        studio: 'LHEA and the Word Spirit',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'LHEA and the Word Spirit',
        studio: 'Cooking Battles',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Cooking Battles',
        studio: 'Rainbow Six Mobile',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Rainbow Six Mobile',
        studio: 'EA Sports FC 26 Mobile',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'EA Sports FC 26 Mobile',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestvrgame',
    title: 'Best VR/AR Game',
    description:
      'The Canadian Game Award for Best VR/AR Game recognizes excellence in virtual and augmented reality gaming experiences.',
    nominees: [
      {
        id: '1',
        title: 'Verse VR',
        studio: 'Elsewhere Electric',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Elsewhere Electric',
        studio: 'Fruit Golf',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Fruit Golf',
        studio: 'Chronostrike',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Chronostrike',
        studio: 'Prison Boss Prohibition',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Prison Boss Prohibition',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestindiegame',
    title: 'Best Indie Game',
    description:
      'The Canadian Game Award for Best Indie Game recognizes excellence in independent game development, considering innovation, creativity, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: 'Ambrosia Sky: Act One',
        studio: 'Ctrl Alt Deal',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Ctrl Alt Deal',
        studio: 'Wanderstop',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Wanderstop',
        studio: 'Fresh Tracks',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Fresh Tracks',
        studio: 'Marvel Cosmic Invasion',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Marvel Cosmic Invasion',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'studiooftheyear',
    title: 'Studio of the Year',
    description:
      "The Canadian Game Award for Studio of the Year recognizes a Canadian studio that represents the impeccable pool of talent the country supports. This studio launched a brand new, engaging game into the market. Studio of the Year identifies a development house that's fostered positivity and created an impact within the industry thanks to its passion, dedication, and vision.",
    nominees: [
      {
        id: '1',
        title: 'Compulsion Games',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Rogue Factor',
        studio: 'Tribute Games',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Tribute Games',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Yellow Brick Games',
        studio: 'Digital Extremes',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Digital Extremes',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'gameoftheyear',
    title: 'Game of the Year',
    description:
      'The Canadian Game Award for Game of the Year recognizes a trailblazing title that embodies cutting-edge design, technical performance, and innovative entertainment. Game of the Year is a crowning achievement in Canadian game development, raising the bar in games.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Battlefield 6',
        imageUrl: '/images/nominees/yOdjg4nHZlrSGJFAQBrNR2BY.avif',
        link: 'https://store.steampowered.com/app/1430220/BIOMORPH/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Battlefield 6',
        studio: 'South of Midnight',
        imageUrl: '/images/nominees/EmOAPyy74AQeagXuf620wp1Qw.avif',
        link: 'https://store.steampowered.com/app/1924360/Lil_Guardsman/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: 'Hell is Us',
        imageUrl: '/images/nominees/tVZfzyrB838sBQGQlm8JUZ4jlU.avif',
        link: 'https://store.steampowered.com/app/1065070/t/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Hell is Us',
        studio: 'Lost Records: Bloom & Rage',
        imageUrl: '/images/nominees/58nVxcI9XUFNFgzXZKoQGhX5NQ.avif',
        link: 'https://store.steampowered.com/agecheck/app/1845910/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Lost Records: Bloom & Rage',
        studio: '',
        imageUrl: '/images/nominees/kSY2Ls1CpfmHIccncV77g6G8.avif',
        link: 'https://store.steampowered.com/app/1675830/1000xRESIST/',
        isWinner: false,
      },
    ],
  },
];

export default function Ehgameexpo() {
  return (
    <section className="bg-[#5630bf]">
      <CategoriesHero />
      {allCategories.map((category) => (
        <NomineeSection
          key={category.id}
          categoryId={category.id}
          categoryTitle={category.title}
          categoryDescription={category.description}
          nominees={category.nominees}
        />
      ))}
    </section>
  );
}
