import CategoriesGrid from '@/components/CategoriesGrid';
import CategoriesHero from '@/components/CategoriesHero';
import NomineeSection from '@/components/NomineeSection';

const allCategories = [
  {
    id: 'bestartdirection',
    title: 'Best Art Direction',
    description:
      'The Canadian Game Award for Best Art Direction recognizes the achievement for an art direction in games. Judges will be looking at the quality of the visual and its consistency across all aspects of game production. They will look at the visual signature, its uniqueness, the animation, rendering and impact on storytelling, as well as its high level of immersion in the game environment or story.',
    nominees: [
      {
        id: '1',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Lost Records: Bloom & Rage',
        studio: "DON'T NOD",
        imageUrl: '/images/nominees/lost_records.jpg',
        link: 'https://store.steampowered.com/app/1902960/Lost_Records_Bloom__Rage/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/new/eternal-strands.webp',
        link: 'https://store.steampowered.com/app/1491410/Eternal_Strands/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Marvel Cosmic Invasion',
        studio: 'Tribute Games',
        imageUrl: '/images/nominees/cosmic invasion.jfif',
        link: 'https://store.steampowered.com/app/2753970/MARVEL_Cosmic_Invasion/',
        isWinner: false,
      },
      {
        id: '5',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestgamedesign',
    title: 'Best Game Design',
    description:
      'The Canadian Game Award for Best Game Design recognizes the achievement for game design in a video game. It looks at its innovative side, its features depending on the platform, the experience it offers as well as its level of engagement in a genre, or if it defines a new genre/new standards.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/hell_is_us.jpg',
        link: 'https://store.steampowered.com/app/1620730/Hell_is_Us/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/new/eternal-strands.webp',
        link: 'https://store.steampowered.com/app/1491410/Eternal_Strands/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/new/battle_field_6.jpg',
        link: 'https://store.steampowered.com/app/2807960/Battlefield_6/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestscore',
    title: 'Best Score/Soundtrack',
    description:
      'The Canadian Game Award for Best Score/Soundtrack recognizes the achievement for a game soundtrack. It has to present a high quality of integration within the game as well as its impact on the game experience.',
    nominees: [
      {
        id: '1',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Lost Records: Bloom & Rage',
        studio: "DON'T NOD",
        imageUrl: '/images/nominees/lost_records.jpg',
        link: 'https://store.steampowered.com/app/1902960/Lost_Records_Bloom__Rage/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Eternal Strands',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/new/eternal-strands.webp',
        link: 'https://store.steampowered.com/app/1491410/Eternal_Strands/',
        isWinner: false,
      },
      {
        id: '4',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Marvel Cosmic Invasion',
        studio: 'Tribute Games',
        imageUrl: '/images/nominees/cosmic invasion.jfif',
        link: 'https://store.steampowered.com/app/2753970/MARVEL_Cosmic_Invasion/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestperformance',
    title: 'Best Performance',
    description:
      'The Canadian Game Award for Best Performance recognizes the achievement for character performance in a game. It has to demonstrate an original, creative and engaging performance that creates an indelible impression and contributes to a compelling experience. The judges will also consider the quality of voice artistry and motion capture (if applicable).',
    nominees: [
      {
        id: '1',
        title: 'Elias Toufexis (Hell is Us)',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/Elias_Toufexis.webp',
        link: 'https://www.imdb.com/name/nm1340118/',
        isWinner: false,
      },
      {
        id: '2',
        title: "Peter Shinkoda (Assassin's Creed Shadows)",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/new/PeterShinkoda.webp',
        link: 'https://www.imdb.com/name/nm0793946/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Olivia Lepore (Bloom & Rage)',
        studio: "DON'T NOD",
        imageUrl: '/images/nominees/olivia_leore.jfif',
        link: 'https://www.imdb.com/name/nm12244422/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Erica Luttrell (Battlefield 6)',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/erica_luttrell.jfif',
        link: 'https://www.imdb.com/name/nm0527518/',
        isWinner: false,
      },
      {
        id: '5',
        title: "Momona Tamada (Assassin's Creed Shadows)",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/momona tamanda.jpg',
        link: 'https://www.imdb.com/name/nm10113394/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestnarrative',
    title: 'Best Narrative',
    description:
      'The Canadian Game Award for Best Narrative recognizes the achievement for a game narrative. It will be awarded based on the story and vision, as well as the dialogues (if applicable) and the emotional impact of the story on the player.',
    nominees: [
      {
        id: '1',
        title: 'Lost Records: Bloom & Rage',
        studio: "DON'T NOD",
        imageUrl: '/images/nominees/lost_records.jpg',
        link: 'https://store.steampowered.com/app/1902960/Lost_Records_Bloom__Rage/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/hell_is_us.jpg',
        link: 'https://store.steampowered.com/app/1620730/Hell_is_Us/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '4',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Wanderstop',
        studio: 'Ivy Road',
        imageUrl: '/images/nominees/wander_stop.jfif',
        link: 'https://store.steampowered.com/app/1299460/Wanderstop/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestaudiodesign',
    title: 'Best Audio Design',
    description:
      'The Canadian Game Award for Best Audio Design recognizes the achievement for audio design in a game. Judges will be looking at its coherence with the title/brand, its immersiveness, quality of integration and of composition.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Hell is Us',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/hell_is_us.jpg',
        link: 'https://store.steampowered.com/app/1620730/Hell_is_Us/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Eternal Strands',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/new/eternal-strands.webp',
        link: 'https://store.steampowered.com/app/1491410/Eternal_Strands/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/new/battle_field_6.jpg',
        link: 'https://store.steampowered.com/app/2807960/Battlefield_6/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsplayer',
    title: 'Best Esports Player',
    description:
      'The Canadian Game Award for Esports Player recognizes the impact of an esport player within their community, and their overall performance in the game they play.',
    nominees: [
      {
        id: '1',
        title: 'Dashy',
        studio: 'OpTic Texas',
        imageUrl: '/images/nominees/dashy_1.jfif',
        link: 'https://x.com/DashySZN',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Twistzz',
        studio: 'FaZe Clan',
        imageUrl: '/images/nominees/russel.webp',
        link: 'https://x.com/Twistzz',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Canadian',
        studio: 'Shopify Rebellion',
        imageUrl: '/images/nominees/canadian_troy.jfif',
        link: 'https://x.com/BIGBADNADIAN',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Mada',
        studio: 'NRG',
        imageUrl: '/images/nominees/new/adam.webp',
        link: 'https://x.com/madafps',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Sarah',
        studio: 'Shopify Rebellion Gold',
        imageUrl: '/images/nominees/sarah_simpson.webp',
        link: 'https://x.com/sarah_frags',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsevent',
    title: 'Best Esports Event',
    description: '',
    nominees: [
      {
        id: '1',
        title: 'Valorant Masters Toronto 2025',
        studio: 'Electric Clash 2025',
        imageUrl: '/images/nominees/valorant_masters.png',
        link: 'https://liquipedia.net/valorant/VCT/2025/Stage_2/Masters',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Electric Clash 2025',
        studio: 'Battle of BC 7',
        imageUrl: '/images/nominees/new/electric_crash_2025.webp',
        link: 'https://liquipedia.net/fighters/Electric_Clash/2025/T8',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Battle of BC 7',
        studio: 'Raptors GC Tournament',
        imageUrl: '/images/nominees/battle_of_7.png',
        link: 'https://liquipedia.net/smash/Battle_of_BC/7/Ultimate',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Raptors GC Tournament',
        studio: 'Call of Duty Champs',
        imageUrl: '/images/nominees/raptors.jpg',
        link: 'https://x.com/RaptorsGC',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Call of Duty Champs',
        studio: '',
        imageUrl: '/images/nominees/new/call_of_duty_2025.webp',
        link: 'https://cod-esports.fandom.com/wiki/Call_of_Duty_League_Championship_2025',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportscoach',
    title: 'Best Esports Coach',
    description:
      'The Canadian Game Award for Esports Coach recognizes excellence in coaching and team development within the esports community.',
    nominees: [
      {
        id: '1',
        title: 'Loic "Effys" Sauvageau',
        studio: 'Shopify Rebellion',
        imageUrl: '/images/nominees/efffys.jfif',
        link: 'https://x.com/effysgo',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Antonin Tran',
        studio: 'AEC',
        imageUrl: '/images/nominees/new/antonin_tran.jpeg',
        link: 'https://www.linkedin.com/in/antonin-tran/?locale=en',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Dayos',
        studio: 'Luminosity Gaming',
        imageUrl: '/images/nominees/dayos.webp',
        link: 'https://x.com/MvlDayos',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Shaun Byrne',
        studio: 'St. Clair Saints',
        imageUrl: '/images/nominees/shaun.jfif',
        link: 'https://x.com/TheEsportsProf',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Aui_2000',
        studio: 'Team Falcons',
        imageUrl: '/images/nominees/Aui_2000.jfif',
        link: 'https://x.com/Aui_2000',
        isWinner: false,
      },
    ],
  },
  {
    id: 'esportsorg',
    title: 'Best Esports and Gaming Organization',
    description:
      'The Canadian Game Award for Esports Org recognizes the engagement and positive impact in their community, as well as their overall player performances across games.',
    nominees: [
      {
        id: '1',
        title: 'Shopify Rebellion',
        studio: 'Toronto Ultra / KOI / OverActive Media',
        imageUrl:
          '/images/nominees/new/Shopify_Rebellion_Logo_2021_alternative-s5120.png',
        link: 'https://shopifyrebellion.gg/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Toronto Ultra / KOI / OverActive Media',
        studio: 'Vancouver Surge',
        imageUrl: '/images/nominees/new/overractive_media.webp',
        link: 'https://overactivemedia.com/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Vancouver Surge',
        studio: 'Raptors GC',
        imageUrl: '/images/nominees/Seattle_Surge.svg',
        link: 'https://x.com/SurgeVancouver',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Raptors GC',
        studio: '',
        imageUrl: '/images/nominees/raptors.jpg',
        link: 'https://x.com/RaptorsGC',
        isWinner: false,
      },
    ],
  },
  {
    id: 'contentcreator',
    title: 'Best Content Creator/Show',
    description: '',
    nominees: [
      {
        id: '1',
        title: 'Victor Lucas / Electric Playground',
        studio: 'NickEh30 (Nicholas Amyoony)',
        imageUrl: '/images/nominees/new/victor_lucas.jpg',
        link: 'https://x.com/Victor_Lucas?lang=en',
        isWinner: false,
      },
      {
        id: '2',
        title: 'NickEh30 (Nicholas Amyoony)',
        studio: 'Shroud (Michael Grzesiek)',
        imageUrl: '/images/nominees/new/nick amo.webp',
        link: 'https://x.com/NickEh30',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Shroud (Michael Grzesiek)',
        studio: 'Stef Sanjati',
        imageUrl: '/images/nominees/new/michael_Shroud_cropped.jpg',
        link: 'https://x.com/shroud',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Stef Sanjati',
        studio: 'Typical Gamer (Andre Rebelo)',
        imageUrl: '/images/nominees/new/stef_sanjati.jpg',
        link: 'https://x.com/stefsanjati?lang=en',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Typical Gamer (Andre Rebelo)',
        studio: '',
        imageUrl: '/images/nominees/new/andrew_robole.webp',
        link: 'https://x.com/TypicalGamer',
        isWinner: false,
      },
    ],
  },
  {
    id: 'beststreamer',
    title: 'Best Streamer',
    description: '',
    nominees: [
      {
        id: '1',
        title: 'Shroud (Michael Grzesiek)',
        studio: 'xQc (Felix Lengyel)',
        imageUrl: '/images/nominees/new/michael_Shroud_cropped.jpg',
        link: 'https://x.com/shroud',
        isWinner: false,
      },
      {
        id: '2',
        title: 'xQc (Felix Lengyel)',
        studio: 'NickEh30 (Nicholas Amyoony)',
        imageUrl: '/images/nominees/new/felix_lengyel.jpg',
        link: 'https://x.com/xQc',
        isWinner: false,
      },
      {
        id: '3',
        title: 'NickEh30 (Nicholas Amyoony)',
        studio: 'Typical Gamer (Andre Rebelo)',
        imageUrl: '/images/nominees/new/nick amo.webp',
        link: 'https://x.com/NickEh30',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Typical Gamer (Andre Rebelo)',
        studio: 'Ashley Roboto',
        imageUrl: '/images/nominees/new/andrew_robole.webp',
        link: 'https://x.com/TypicalGamer',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Ashley Roboto',
        studio: '',
        imageUrl: '/images/nominees/new/ashley_roboto.jpeg',
        link: 'https://x.com/AshleyRoboto',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestpersonality',
    title: 'Best Personality',
    description: '',
    nominees: [
      {
        id: '1',
        title: 'Jennifer Pitchette (LemonKiwi)',
        studio: 'Victor Lucas',
        imageUrl: '/images/nominees/new/JenniferLemonKiwi2019Headshot.jpg',
        link: 'https://x.com/LemonKiwi_',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Victor Lucas',
        studio: 'Stef Sanjati',
        imageUrl: '/images/nominees/new/victor_lucas.jpg',
        link: 'https://x.com/Victor_Lucas?lang=en',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Stef Sanjati',
        studio: 'Vansilli / Alex "Vansilli" Nguyen',
        imageUrl: '/images/nominees/new/stef_sanjati.jpg',
        link: 'https://x.com/stefsanjati?lang=en',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Vansilli / Alex "Vansilli" Nguyen',
        studio: 'Shroud (Michael Grzesiek)',
        imageUrl: '/images/nominees/vansilli.jfif',
        link: 'https://x.com/Vansilli',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Shroud (Michael Grzesiek)',
        studio: '',
        imageUrl: '/images/nominees/new/michael_Shroud_cropped.jpg',
        link: 'https://x.com/shroud',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestpcgame',
    title: 'Best PC Game',
    description:
      'The Canadian Game Award for Best PC Game recognizes excellence in PC gaming, considering factors like gameplay, graphics, innovation, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: 'Aloft',
        studio: 'Astrolabe Interactive',
        imageUrl: '/images/nominees/new/aloft.avif',
        link: 'https://store.steampowered.com/app/1660080/Aloft/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Foundation',
        studio: 'Polymorph Games',
        imageUrl: '/images/nominees/new/foundation_game.png',
        link: 'https://store.steampowered.com/app/690830/Foundation/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Ambrosia Sky: Act One',
        studio: 'Soft Rains',
        imageUrl: '/images/nominees/new/ambrosia-sky.jpg',
        link: 'https://store.steampowered.com/app/3580160/Ambrosia_Sky_Act_One/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Eternal Strands',
        studio: 'Yellow Brick Games',
        imageUrl: '/images/nominees/new/eternal-strands.webp',
        link: 'https://store.steampowered.com/app/1491410/Eternal_Strands/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Battlefield 6',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/new/battle_field_6.jpg',
        link: 'https://store.steampowered.com/app/2807960/Battlefield_6/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestconsolegame',
    title: 'Best Console Game',
    description:
      'The Canadian Game Award for Best Console Game recognizes excellence in console gaming, considering factors like gameplay, graphics, innovation, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Battlefield 6',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/new/battle_field_6.jpg',
        link: 'https://store.steampowered.com/app/2807960/Battlefield_6/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Marvel Cosmic Invasion',
        studio: 'Tribute Games',
        imageUrl: '/images/nominees/cosmic_invasion.jfif',
        link: 'https://store.steampowered.com/app/2753970/MARVEL_Cosmic_Invasion/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Hell is Us',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/hell_is_us.jpg',
        link: 'https://store.steampowered.com/app/1620730/Hell_is_Us/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestmobilegame',
    title: 'Best Mobile Game',
    description:
      'The Canadian Game Award for Best Mobile Game recognizes excellence in mobile gaming, considering factors like gameplay, graphics, innovation, and overall player experience on mobile platforms.',
    nominees: [
      {
        id: '1',
        title: 'Elsewhere Electric',
        studio: 'Games by Stitch',
        imageUrl: '/images/nominees/new/else_where_electric.png',
        link: 'https://store.steampowered.com/app/3439970/Elsewhere_Electric/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'LHEA and the Word Spirit',
        studio: 'Soul Fuel Games',
        imageUrl: '/images/nominees/lhea.jpg',
        link: 'https://store.steampowered.com/app/3572530/LHEA_and_the_Word_Spirit/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Cooking Battles',
        studio: 'Gamemakerone',
        imageUrl: '/images/nominees/new/cooking battles.png',
        link: 'https://cooking-battle.en.softonic.com/android',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Rainbow Six Mobile',
        studio: 'Ubisoft Montréal',
        imageUrl: '/images/nominees/rainbow_six.webp',
        link: 'https://play.google.com/store/apps/details?id=com.ubisoft.rainbowsixmobile.r6.fps.pvp.shooter&hl=en_CA',
        isWinner: false,
      },
      {
        id: '5',
        title: 'EA SPORTS FC™ Mobile Soccer',
        studio: 'EA Vancouver',
        imageUrl: '/images/nominees/new/ea-sports-fc-mobile-logo-png.png',
        link: 'https://play.google.com/store/apps/details?id=com.ea.gp.fifamobile&hl=en_US',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestvrgame',
    title: 'Best VR/AR Game',
    description:
      'The Canadian Game Award for Best VR/AR Game recognizes excellence in virtual and augmented reality gaming experiences.',
    nominees: [
      {
        id: '1',
        title: 'Verse VR',
        studio: 'Lofty Sky Entertainment Inc.',
        imageUrl: '/images/nominees/verse_vr.jpg',
        link: 'https://store.steampowered.com/app/2958710/Verse_VR/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Elsewhere Electric',
        studio: 'Games by Stitch',
        imageUrl: '/images/nominees/new/else_where_electric.png',
        link: 'https://store.steampowered.com/app/3439970/Elsewhere_Electric/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Fruit Golf',
        studio: '', // Not in your mapping, left as empty
        imageUrl: '/images/nominees/new/fruit_golf.jpg',
        link: 'https://www.meta.com/experiences/fruit-golf/3580596948703548/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Chronostrike',
        studio: 'Sketchbox Inc',
        imageUrl: '/images/nominees/new/chrono_strike.jpeg',
        link: 'https://www.meta.com/experiences/chronostrike/24697269806585974/?srsltid=AfmBOoqKCUL91S04OLW9OqjIeaw97v8MoICZHioncTl8kTaG99D-fsaJ',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Prison Boss Prohibition',
        studio: 'Trebuchet',
        imageUrl: '/images/nominees/new/prison-boss-prohibition.webp',
        link: 'https://store.steampowered.com/app/2973830/Prison_Boss_Prohibition/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'bestindiegame',
    title: 'Best Indie Game',
    description:
      'The Canadian Game Award for Best Indie Game recognizes excellence in independent game development, considering innovation, creativity, and overall player experience.',
    nominees: [
      {
        id: '1',
        title: 'Ambrosia Sky: Act One',
        studio: 'Soft Rains',
        imageUrl: '/images/nominees/new/ambrosia-sky.jpg',
        link: 'https://store.steampowered.com/app/3580160/Ambrosia_Sky_Act_One/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Ctrl Alt Deal',
        studio: 'Only By Midnight',
        imageUrl: '/images/nominees/control alt deal.jpg',
        link: 'https://store.steampowered.com/app/2146390/Ctrl_Alt_Deal/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Wanderstop',
        studio: 'Ivy Road',
        imageUrl: '/images/nominees/wander_stop.jfif',
        link: 'https://store.steampowered.com/app/1299460/Wanderstop/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Fresh Tracks',
        studio: 'Buffalo Buffalo',
        imageUrl: '/images/nominees/fresh_tracks.jpg',
        link: 'https://store.steampowered.com/app/3202950/Fresh_Tracks/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Marvel Cosmic Invasion',
        studio: 'Tribute Games',
        imageUrl: '/images/nominees/cosmic invasion.jfif',
        link: 'https://store.steampowered.com/app/2753970/MARVEL_Cosmic_Invasion/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'studiooftheyear',
    title: 'Studio of the Year',
    description:
      "The Canadian Game Award for Studio of the Year recognizes a Canadian studio that represents the impeccable pool of talent the country supports. This studio launched a brand new, engaging game into the market. Studio of the Year identifies a development house that's fostered positivity and created an impact within the industry thanks to its passion, dedication, and vision.",
    nominees: [
      {
        id: '1',
        title: 'Compulsion Games',
        studio: '', // Left empty as it's the studio itself
        imageUrl: '/images/nominees/compulsion_games.jpg',
        link: 'https://compulsiongames.com/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Rogue Factor',
        studio: '', // Left empty as it's the studio itself
        imageUrl: '/images/nominees/new/Rogue_factor.jpg',
        link: 'https://rogue-factor.com/?lang=en',
        isWinner: false,
      },
      {
        id: '3',
        title: 'Tribute Games',
        studio: '', // Left empty as it's the studio itself
        imageUrl: '/images/nominees/new/tribute_games.jpg',
        link: 'https://tributegames.com/index.html',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Yellow Brick Games',
        studio: '', // Left empty as it's the studio itself
        imageUrl: '/images/nominees/yellow_brick.jpg',
        link: 'https://yellowbrickgames.ca/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Digital Extremes',
        studio: '', // Left empty as it's the studio itself
        imageUrl: '/images/nominees/new/Digital-Extremes-W-T-1.png',
        link: 'https://www.digitalextremes.com/',
        isWinner: false,
      },
    ],
  },
  {
    id: 'gameoftheyear',
    title: 'Game of the Year',
    description:
      'The Canadian Game Award for Game of the Year recognizes a trailblazing title that embodies cutting-edge design, technical performance, and innovative entertainment. Game of the Year is a crowning achievement in Canadian game development, raising the bar in games.',
    nominees: [
      {
        id: '1',
        title: "Assassin's Creed Shadows",
        studio: 'Ubisoft Québec',
        imageUrl: '/images/nominees/assasin greed shadows.jfif',
        link: 'https://store.steampowered.com/app/3159330/Assassins_Creed_Shadows/',
        isWinner: false,
      },
      {
        id: '2',
        title: 'Battlefield 6',
        studio: 'Motive Studio',
        imageUrl: '/images/nominees/new/battle_field_6.jpg',
        link: 'https://store.steampowered.com/app/2807960/Battlefield_6/',
        isWinner: false,
      },
      {
        id: '3',
        title: 'South of Midnight',
        studio: 'Compulsion Games',
        imageUrl: '/images/nominees/south_of_midnight.jfif',
        link: 'https://store.steampowered.com/app/1934570/South_of_Midnight/',
        isWinner: false,
      },
      {
        id: '4',
        title: 'Hell is Us',
        studio: 'Rogue Factor',
        imageUrl: '/images/nominees/new/hell_is_us.jpg',
        link: 'https://store.steampowered.com/app/1620730/Hell_is_Us/',
        isWinner: false,
      },
      {
        id: '5',
        title: 'Lost Records: Bloom & Rage',
        studio: "DON'T NOD",
        imageUrl: '/images/nominees/lost_records.jpg',
        link: 'https://store.steampowered.com/app/1902960/Lost_Records_Bloom__Rage/',
        isWinner: false,
      },
    ],
  },
];

export default function Ehgameexpo() {
  return (
    <section className="bg-[#5630bf]">
      <CategoriesHero />
      {allCategories.map((category) => (
        <NomineeSection
          key={category.id}
          categoryId={category.id}
          categoryTitle={category.title}
          categoryDescription={category.description}
          nominees={category.nominees}
        />
      ))}
    </section>
  );
}
